---
title: "Metaphor data analysis"
author: "Ramin and Aminul"
date: "2023-09-01"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r}
library(readxl)
crit <- read_xlsx("data 2.xlsx")
str(crit)
```


```{r}
library(ordinal)
library(ggplot2)
library(tidyverse)
library(lme4)
library(dplyr)
library(RColorBrewer)
library(tidyr)
```




```{r}
crit$score<- as.numeric(crit$score)
data.to.plot.Q1 <- crit %>%
group_by(QUESTNNR, Nationality, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```

```{r}
ggplot(data = data.to.plot.Q1 , aes(x= score, y=prop, fill=QUESTNNR,  na.rm = TRUE)) + 
  geom_bar(stat="identity", na.rm = TRUE) +
  geom_errorbar(aes(ymin = prop+lowerE, ymax = prop+upperE))+
  
  theme(text = element_text(size=14))+
  facet_wrap(~Nationality+QUESTNNR, nrow = 2)+
  theme(
    strip.background = element_blank(),
    strip.text.y = element_blank())+ 
  theme_classic() +
  theme(text = element_text(size=10))+
  scale_fill_manual(values=c('#999999','#E69F00'))+
  labs(title="", x="Question scales", y = "proportion of response")+
  scale_x_continuous(breaks=seq(1:7))
```

```{r}

crit$score<- as.numeric(crit$score)
data.to.plot.Q2 <- crit %>%
group_by(Nationality, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```



```{r}
# Create the graph
ggplot(data = data.to.plot.Q2 , aes(x= score, y=prop, fill=Nationality, na.rm = TRUE)) +
  geom_bar(stat="identity", na.rm = TRUE,  position=position_dodge())


```


```{r}

crit$Edu_level<- as.numeric(crit$Edu_level)
data.to.plot.Q3 <- crit %>%
group_by(QUESTNNR, Edu_level, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```




```{r}
# Reorder Edu_level as a factor with appropriate labels
data.to.plot.Q3$Edu_level <- factor(data.to.plot.Q3$Edu_level, levels = 1:7, labels = c("Primary", "Secondary", "College", "Vocational", "Admission", "Tertiary", "Other"))

# Plotting code (include this after the data preparation step)
ggplot(data = data.to.plot.Q3, aes(x = Edu_level, y = prop)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_x_discrete(drop = FALSE) +
  coord_cartesian(ylim = c(0, NA)) + 
  theme_classic() +
  labs(title="", x="Education level", y = "proportion of response")

```


```{r}
crit$Edu_level<- as.numeric(crit$Edu_level)
data.to.plot.Q4 <- crit %>%
group_by(QUESTNNR, Nationality, Edu_level, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```

```{r}

# Reorder Edu_level as a factor with appropriate labels
data.to.plot.Q4$Edu_level <- factor(data.to.plot.Q4$Edu_level, levels = 1:7, labels = c("Primary", "Secondary", "College", "Vocational", "Admission", "Tertiary", "Other"))

# Create the graph
ggplot(data = data.to.plot.Q4 , aes(x = Edu_level, y = prop, fill = Nationality)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_x_discrete(drop = FALSE) +
  coord_cartesian(ylim = c(0, NA)) + 
  theme_classic() + 
  labs(title="", x="Education level", y = "proportion of response")

```


```{r}
crit$Edu_level<- as.numeric(crit$Edu_level)
data.to.plot.Q5 <- crit %>%
group_by(QUESTNNR, Nationality, Edu_level, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```



```{r}

# Convert Edu_level to a factor with complete levels
data.to.plot.Q5$Edu_level <- factor(data.to.plot.Q5$Edu_level, levels = c("1", "2", "3", "4", "5", "6", "7"), labels = c("Primary", "Secondary", "Tertiary", "Vocational", "Admission", "College", "Other"))


ggplot(data = data.to.plot.Q5, aes(x = Edu_level, y = prop, fill = QUESTNNR, na.rm = TRUE)) + 
  geom_point(stat = "identity", na.rm = TRUE, width = 1) +
  geom_errorbar(aes(ymin = prop, ymax = prop + upperE), width = 0.05, linewidth = 0.6, size = I(0.5)) +
  facet_wrap(~Nationality + QUESTNNR, nrow = 2) +
  scale_x_discrete(drop = FALSE) +
  coord_cartesian(ylim = c(0, NA)) + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_fill_manual(values = c('#999999', '#E69F00')) + 
  labs(title = "", x = "Education level", y = "proportion of responses") + 
  geom_smooth(data = data.to.plot.Q5, aes(group = QUESTNNR), method = "lm", color = "black", linetype = "solid")

  
```

```{r}
data.to.plot <- crit %>%
group_by(QUESTNNR, Nationality, item, score) %>% #group
summarise(num=n()) %>% 
mutate(prop = num / sum(num), 
upperE=1.96*sqrt((prop*(1-prop))/sum(num)),lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```

``` {r}
# Subset your data for 'SQ01' to 'SQ11'
subset_data <- data.to.plot[data.to.plot$item %in% c('SQ01', 'SQ02', 'SQ03', 'SQ04', 'SQ05', 'SQ06', 'SQ07', 'SQ08', 'SQ09', 'SQ10', 'SQ11'), ]

# Create a ggplot for 'SQ01' to 'SQ11'
ggplot(data = subset_data, aes(x = score, y = prop, fill = QUESTNNR, na.rm = TRUE)) +
  geom_bar(stat = "identity", na.rm = TRUE, width = 1) +
  geom_errorbar(aes(ymin = prop + lowerE, ymax = prop + upperE), width = 0.05, size = I(0.5)) +

  facet_wrap(~item + Nationality) +
  theme_classic() +
  theme(text = element_text(size = 6)) +
  scale_fill_manual(values = c('#999999', '#E69F00')) +
  labs(title = "", x = "Perception", y = "Proportion of response") +
  scale_x_continuous(breaks = seq(1:7))

```

``` {r}
# Subset your data for 'SQ11' to 'SQ22'
subset_data <- data.to.plot[data.to.plot$item %in% c('SQ12', 'SQ13', 'SQ14', 'SQ15', 'SQ16', 'SQ17', 'SQ18', 'SQ19', 'SQ20', 'SQ21', 'SQ22'), ]

# Create a ggplot for 'SQ01' to 'SQ11'
ggplot(data = subset_data, aes(x = score, y = prop, fill = QUESTNNR, na.rm = TRUE)) +
  geom_bar(stat = "identity", na.rm = TRUE, width = 1) +
  geom_errorbar(aes(ymin = prop + lowerE, ymax = prop + upperE), width = 0.05, size = I(0.5)) +
  
  facet_wrap(~item + Nationality, nrow = 5) +

  theme_classic() +
  theme(text = element_text(size = 6)) +
  scale_fill_manual(values = c('#999999', '#E69F00')) +
  labs(title = "", x = "Perception", y = "Proportion of response") 

```



```{r}
data.to.plot$QuestionGroup <- case_when(
 data.to.plot$item %in% c('SQ03', 'SQ22') ~ 'Equipment and support'
)

# Create a new data frame
data.to.plot.reversibility <- data.to.plot %>%
  filter(QuestionGroup == 'Equipment and support')

# Plot the data
ggplot(data = data.to.plot.reversibility, aes(x = score, y = prop, fill = QUESTNNR, na.rm = TRUE)) +
  geom_bar(stat = "identity", na.rm = TRUE, position=position_dodge())+
  theme(text = element_text(size=14))
```

```{r}
data.to.plot <- crit %>%
  group_by(QUESTNNR, Nationality, item, score) %>% #group
  summarise(num=n()) %>% 
  mutate(prop = num / sum(num),
         prop_percent = prop * 100,
         upperE=1.96*sqrt((prop*(1-prop))/sum(num)),
         lowerE=-1.96*sqrt((prop*(1-prop))/sum(num)))
```

```{r}
data.to.plot$QuestionGroup <- case_when(
  data.to.plot$item %in% c('SQ09', 'SQ13', 'SQ14', 'SQ20') ~ 'Reversibility',
  data.to.plot$item %in% c('SQ03', 'SQ22') ~ 'Equipment and support',
  
  data.to.plot$item %in% c('SQ01', 'SQ02', 'SQ04', 'SQ05', 'SQ07', 'SQ12', 'SQ15', 'SQ16', 'SQ17') ~ 'Alarming and Critical',
  data.to.plot$item %in% c('SQ08', 'SQ11') ~ 'Trust',
  data.to.plot$item %in% c('SQ10') ~ 'Distrust',
  data.to.plot$item %in% c('SQ19') ~ 'cause',
  data.to.plot$item %in% c('SQ21') ~ 'Human role',
  data.to.plot$item %in% c('SQ06','SQ18') ~ 'Immediacy and Urgency',
 
)

ggplot(data = data.to.plot , aes(x= score, y=prop, fill=QUESTNNR,  na.rm = TRUE)) + 
  geom_bar(stat = "identity", na.rm = TRUE,  position=position_dodge()) +


facet_wrap(~ QuestionGroup + Nationality, nrow = 4) +

theme_classic() +
theme(text = element_text(size = 7)) +
scale_fill_manual(values = c('#999999', '#E69F00')) +
labs(title = "", x = "Perception", y = "Proportion of response") 


```
```{r}
print(data.to.plot$prop)

```




```{r}

#Factor coding and contrasts
crit$scoref <- factor(crit$score)
crit$QUESTNNR <- factor(crit$QUESTNNR)
crit$Nationality <- factor(crit$Nationality)
crit$item <- factor(crit$item)
crit$QUESTNNR <- relevel(crit$QUESTNNR, ref = "Science")
crit$Nationality <- relevel(crit$Nationality, ref = "American")
contrasts(crit$QUESTNNR) <- "contr.sum"
contrasts(crit$Nationality) <- "contr.sum"

#clmm analysis
m1 <- clmm(scoref ~ QUESTNNR * Nationality + (1 + QUESTNNR * Nationality | item), data = crit)
summary(m1)



#Likelihood ratio tests
m0 <- clmm(scoref ~ Nationality + (1 | item), data = crit)
summary(m0)

#m1 <- clmm(scoref ~ Nationality + QUESTNNR + (1 | item), data = crit)
#summary(m1)

m1 <- clmm(scoref ~ QUESTNNR * Nationality + (1 + QUESTNNR * Nationality | item) + (1 + QUESTNNR * Nationality | SERIAL) , data = crit)
m2 <- clmm(scoref ~ Nationality * QUESTNNR + (1 | item), data = crit)
summary(m2)



#gender

m3 <- clmm(scoref ~ Gender + QUESTNNR + Nationality + (1 | SERIAL), data = crit)

# Print the model summary
summary(m3)

# Education level clmm model
m4 <- clmm(scoref ~ Edu_level + Nationality + QUESTNNR + Edu_level:Nationality + Edu_level:QUESTNNR + (1 | SERIAL), data = crit)

# Print the model summary
summary(m4)

# full model

m5 <- clmm(scoref ~ QUESTNNR + Nationality + Edu_level + Gender + Edu_level:Nationality + Edu_level:QUESTNNR + Nationality:QUESTNNR + Edu_level:Nationality:QUESTNNR + (1 | SERIAL), data = crit)
# Print the model summary
summary(m5)


#Age 

m6 <- clmm(scoref ~ Age + QUESTNNR + Age:QUESTNNR + (1 | SERIAL), data = crit)

# Print the model summary
summary(m6)



#anova
anova(m1, m0)
anova(m1, m2)
```








